//! The grid itself.

use crate::palette::Palette;

/// The largest edge a model may have.
///
/// 256 is where the coordinate stops fitting in the `u8` the `.vox` voxel
/// record uses, so it is the real interoperability ceiling rather than an
/// arbitrary one. The editor's own default is 64 — see `voxeler`'s `--size`.
pub const MAX_DIM: u16 = 256;

/// A dense grid of palette indices, plus the palette they index.
///
/// `voxels` is x-major: index `x + y * sx + z * sx * sy`. That ordering means a
/// run along X — the direction face extraction and the rasterizer both scan —
/// is contiguous.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct VoxelModel {
    size: [u16; 3],
    voxels: Vec<u8>,
    palette: Palette,
}

impl VoxelModel {
    /// An empty model. Panics on a zero or oversized edge: every caller either
    /// hard-codes the size or has already validated it against [`MAX_DIM`],
    /// so a `Result` here would be a `.unwrap()` at every call site.
    pub fn new(sx: u16, sy: u16, sz: u16) -> Self {
        assert!(
            sx > 0 && sy > 0 && sz > 0,
            "a model needs a positive size, got {sx}x{sy}x{sz}"
        );
        assert!(
            sx <= MAX_DIM && sy <= MAX_DIM && sz <= MAX_DIM,
            "{sx}x{sy}x{sz} exceeds the {MAX_DIM} limit"
        );
        Self {
            size: [sx, sy, sz],
            voxels: vec![0; sx as usize * sy as usize * sz as usize],
            palette: Palette::default(),
        }
    }

    pub fn size(&self) -> [u16; 3] {
        self.size
    }

    pub fn palette(&self) -> &Palette {
        &self.palette
    }

    pub fn palette_mut(&mut self) -> &mut Palette {
        &mut self.palette
    }

    pub fn set_palette(&mut self, palette: Palette) {
        self.palette = palette;
    }

    /// Whether a *signed* coordinate names a cell. Signed because every caller
    /// arrives from arithmetic that can go negative — a neighbour lookup at
    /// x = 0, a face offset — and doing the check on unsigned types means each
    /// of those has to guard the cast first.
    pub fn contains(&self, x: i32, y: i32, z: i32) -> bool {
        x >= 0
            && y >= 0
            && z >= 0
            && x < self.size[0] as i32
            && y < self.size[1] as i32
            && z < self.size[2] as i32
    }

    fn index(&self, x: i32, y: i32, z: i32) -> usize {
        x as usize + y as usize * self.size[0] as usize + z as usize * self.size[0] as usize * self.size[1] as usize
    }

    /// The palette index at a cell, or 0 (air) outside the grid.
    ///
    /// Out-of-bounds reading as air is what lets face extraction ask about a
    /// neighbour without a bounds test of its own: the outside of the model is
    /// air, so its boundary faces are generated by the same rule as every
    /// interior one.
    pub fn get(&self, x: i32, y: i32, z: i32) -> u8 {
        if self.contains(x, y, z) {
            self.voxels[self.index(x, y, z)]
        } else {
            0
        }
    }

    /// Write a cell and report the index that was there. Out of bounds is a
    /// no-op returning 0, so a tool that runs off the edge of the volume simply
    /// does nothing.
    pub fn set(&mut self, x: i32, y: i32, z: i32, value: u8) -> u8 {
        if !self.contains(x, y, z) {
            return 0;
        }
        let i = self.index(x, y, z);
        std::mem::replace(&mut self.voxels[i], value)
    }

    pub fn is_solid(&self, x: i32, y: i32, z: i32) -> bool {
        self.get(x, y, z) != 0
    }

    pub fn clear(&mut self) {
        self.voxels.fill(0);
    }

    /// How many cells are not air.
    pub fn filled_count(&self) -> usize {
        self.voxels.iter().filter(|v| **v != 0).count()
    }

    /// Every solid cell as `(x, y, z, index)`, in storage order.
    pub fn iter_filled(&self) -> impl Iterator<Item = ([u16; 3], u8)> + '_ {
        let [sx, sy, _] = self.size;
        self.voxels
            .iter()
            .enumerate()
            .filter(|(_, v)| **v != 0)
            .map(move |(i, v)| {
                let i = i as u32;
                let (sx, sy) = (sx as u32, sy as u32);
                ([(i % sx) as u16, (i / sx % sy) as u16, (i / (sx * sy)) as u16], *v)
            })
    }

    /// Resize in place, keeping whatever still fits at the same coordinates.
    ///
    /// Anchored at the origin rather than centred: a model's origin is the
    /// corner the renderer and any future scene graph place it by, so keeping
    /// *that* fixed is what makes growing a volume feel like adding room on the
    /// far side instead of shifting the model.
    pub fn resize(&mut self, sx: u16, sy: u16, sz: u16) {
        let mut next = VoxelModel::new(sx, sy, sz);
        next.palette = self.palette.clone();
        for ([x, y, z], v) in self.iter_filled() {
            next.set(x as i32, y as i32, z as i32, v);
        }
        *self = next;
    }

    /// The inclusive bounding box of the solid cells, or `None` when empty.
    /// The editor uses it to frame the camera on a model it just loaded.
    pub fn occupied_bounds(&self) -> Option<([u16; 3], [u16; 3])> {
        let mut min = [u16::MAX; 3];
        let mut max = [0u16; 3];
        let mut any = false;
        for (p, _) in self.iter_filled() {
            any = true;
            for a in 0..3 {
                min[a] = min[a].min(p[a]);
                max[a] = max[a].max(p[a]);
            }
        }
        any.then_some((min, max))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn set_reports_the_previous_index() {
        let mut m = VoxelModel::new(4, 4, 4);
        assert_eq!(m.set(1, 2, 3, 7), 0);
        assert_eq!(m.set(1, 2, 3, 9), 7);
        assert_eq!(m.get(1, 2, 3), 9);
    }

    /// Face extraction leans on this: outside the grid must read as air rather
    /// than panic or wrap into the opposite edge.
    #[test]
    fn outside_the_grid_is_air() {
        let mut m = VoxelModel::new(4, 4, 4);
        m.set(0, 0, 0, 1);
        assert_eq!(m.get(-1, 0, 0), 0);
        assert_eq!(m.get(4, 0, 0), 0);
        assert_eq!(m.set(-1, 0, 0, 5), 0);
        assert_eq!(m.filled_count(), 1);
    }

    /// A non-cubic model is where an index-arithmetic slip shows up: with
    /// sx == sy == sz the strides coincide and a wrong one still round-trips.
    #[test]
    fn indexing_survives_unequal_edges() {
        let mut m = VoxelModel::new(2, 3, 5);
        for x in 0..2 {
            for y in 0..3 {
                for z in 0..5 {
                    m.set(x, y, z, (1 + x + y * 2 + z * 6) as u8);
                }
            }
        }
        for x in 0..2 {
            for y in 0..3 {
                for z in 0..5 {
                    assert_eq!(m.get(x, y, z), (1 + x + y * 2 + z * 6) as u8);
                }
            }
        }
        assert_eq!(m.filled_count(), 30);
    }

    #[test]
    fn iter_filled_reports_the_coordinates_it_was_stored_at() {
        let mut m = VoxelModel::new(2, 3, 5);
        m.set(1, 2, 4, 3);
        assert_eq!(m.iter_filled().collect::<Vec<_>>(), vec![([1, 2, 4], 3)]);
    }

    #[test]
    fn resize_keeps_what_still_fits_at_the_same_place() {
        let mut m = VoxelModel::new(4, 4, 4);
        m.set(0, 0, 0, 1);
        m.set(3, 3, 3, 2);
        m.resize(2, 2, 2);
        assert_eq!(m.get(0, 0, 0), 1);
        assert_eq!(m.filled_count(), 1);
    }

    #[test]
    fn bounds_are_inclusive_and_none_when_empty() {
        let mut m = VoxelModel::new(8, 8, 8);
        assert_eq!(m.occupied_bounds(), None);
        m.set(2, 3, 4, 1);
        m.set(5, 3, 1, 1);
        assert_eq!(m.occupied_bounds(), Some(([2, 3, 1], [5, 3, 4])));
    }
}
